### ISSUE TITLE
Minor allele counts data

### ISSUE THREAD

**Issue by sachalau** [farhat-lab/who-analysis#3]
Hi Sanjana,

I see that you are reading a matrix "minor_allele_counts.npz" that recapitulates the minor allele frequency counts for all the samples.
However I'm not sure I see the code that is used to calculate that matrix from the "grm" data that I'm extracting or did I miss that ?

If you could upload that as well that would be great ! Of course it's not urgent.

**Comment by sanju99** [comment]
Hi Sacha, the code for generating `minor_allele_counts.npz` is the first 84 lines of `sample_numbers.py`. I will make that clearer so that it's easier to find. 

Also, I apologize about not responding to this issue. Github emails me when you comment on an issue, but not when you create one, so I will fix my notification settings.

**Comment by sachalau** [comment]
Sorry I'm was being stupid, I had seen that piece before but couldn't find it again. Thanks !
